name: Build amd64

on:
  push:
    branches: [ master ]
    paths:
      - ".github/workflows/build-amd64.yml"
  pull_request:
    branches: [ master ]
    paths:
      - ".github/workflows/build-amd64.yml"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  draft-release:
    runs-on: ubuntu-20.04
    if: ${{ github.actor != 'dependabot[bot]' }} || github.event_name != 'pull_request'
    steps:
      - name: gh release upload
        run: |
          branch_name=`git branch --show-current`
          commit_hash=`git rev-parse --short HEAD`
          new_tag=$branch_name-$commit_hash
          touch clang-format
          touch clang-tidy
          files=`ls -laR .`
          gh release upload $new_tag $files
